version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kopexa-grc
    name: krn
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
