name: Feature Request
description: Suggest a new feature for the KRN Go package
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

        **Note:** This Go package is the source of truth for KRN implementations.
        Features implemented here should also be ported to the TypeScript package.

        After implementation, please add test cases to the shared fixtures:
        [kopexa-grc/krn-fixtures](https://github.com/kopexa-grc/krn-fixtures)

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: What would the API look like?
      placeholder: |
        ```go
        func (k *KRN) NewMethod() string {
            // ...
        }
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered.

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      options:
        - label: I'm willing to implement this feature
        - label: I will add test cases to [krn-fixtures](https://github.com/kopexa-grc/krn-fixtures)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or code examples.
